MainApp/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = 'MainApp'

# '' keeps it as the blank page, we would like to change it to our own custom homepage
# the name of our view will be index so that is what we will also name our html file
urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment, name='new_comment'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:

    urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('MainApp.urls'))
        ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainApp/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add=True)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')

    # str method allows us to say whatever it is we want to say without it just putting
    # the type of object

    def __str__(self):
        return self.text #on the web page this shows us the actual text OF the object so it's important

class Topping(models.Model):
    # create a FK relationship to the Pizza model to relate to the pizza under toppings
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.text

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text[:50]}..."

class Image(models.Model):
    text = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'images')

    def __str__(self):
        return self.text

MainApp/forms.py
from django import forms
from django.forms import widgets

from .models import Comment, Pizza, Topping

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}

        # A widget is a HTML form element, such as a single-line text box,
        # multi-line text area, or drop down list.
        # Customize the input widget for the field "text" so the text area
        # will be 80 columns wide instead of the default 40
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

        

MainApp/views.py
from django.shortcuts import redirect, render
from .forms import CommentsForm
from .models import Pizza, Topping, Comment

# Create your views here.

def index(request):
    # get and post - don't forget
    # every view processes a request, it needs to know if it is a get or post request
    # based on that we can either write to or read from the database

    return render(request, 'MainApp/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    # we don't really need to order by the date added here but we can

    # create a dictionary with variables you are going to use in your template
    context = {'pizzas':pizzas}


    return render(request, 'MainApp/pizzas.html', context) #this will populate the data on the template to render it to the browser


def pizza(request,pizza_id):
    #just like we did in MyShell.py
    pizza = Pizza.objects.get(id=pizza_id)
    #FK can be accessed using '_set'
    toppings = pizza.topping_set.all()
    comments = pizza.comment_set.all()
    context = {'pizza':pizza, 'toppings': toppings, 'comments':comments}

    return render(request, 'MainApp/pizza.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentsForm()
    else:
        form = CommentsForm(data=request.POST)

        if form.is_valid():
            # when we call save(), we include the argument commit = False to tell Django to create
            # a new topping object and assign it to new_topping without saving it
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            form.save()
            return redirect('MainApp:pizza', pizza_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'MainApp/new_comment.html', context)



    

MainApp/templates/mainapp/base.html
{% load bootstrap4 %} 

<body style="background-color: gray;"></body>

<!doctype html>
<html lang = 'en'> 
<head>
    <meta charset='utf-8'>
    <meta name = "viewport" content = "width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Pizzeria</title>


    {% bootstrap_css %} 
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
 <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{%url 'MainApp:index'%}">
            Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class ="nav-item">
                    <a class="nav-link" href="{% url 'MainApp:pizzas' %}">Pizzas</a></li>
            </ul>
        </div>
    </nav>
<main role = "main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %} 
    </div>
    <div> 
        {% block content %}{% endblock content %} 
    </div>
</main>
</body>
</html>

MainApp/templates/mainapp/index.html
{% extends 'MainApp/base.html' %}

{% block page_header %}

<style type="text/css">
.centerImage
{
    text-align:center;
    display:block;
}
</style>

<p style="text-align:center;"><img src="https://media.istockphoto.com/photos/dig-in-picture-id984990052?k=20&m=984990052&s=612x612&w=0&h=XTtDscddhXTSSt8fNonI8RDaDpr9_8dnsJk6RkMAQ38=" height="350", width="700"></p>

    <div class="jumbotron">
        <h1 class="display-3">Annabella's Pizzeria.</h1>

        <p class="lead">Hand-tossed dough made daily in our kitchen,
            award-winning chefs straight from Italy and locally sourced
            toppings - what more could you want?</p>

        <a class="btn btn-lg btn-primary" href="{% url 'MainApp:pizzas' %}"
        role = "button">Check out our menu! &raquo;</a>
    </div>

{% endblock page_header %}

MainApp/templates/mainapp/new_comment.html
{% extends 'MainApp/base.html' %}

{% block content %}

<p><a href="{% url 'MainApp:pizza' pizza.id %}"> {{pizza}}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'MainApp:new_comment' pizza.id %}" method='post'>

    {% csrf_token %} 
    
    {{ form.as_p }}

    <button name="submit">Add Comment</button>
</form>

{% endblock content %} 

MainApp/templates/mainapp/pizza.html
{% extends 'MainApp/base.html' %}

{% block page_header %}
    <h3>{{ Pizza }}</h3>
{% endblock page_header %} 

{% block content %}

<h1 style="color:white;">{{ pizza }}</h1>
<h3>
<p> Toppings:</p>
</h3>
    {% for topping in toppings %} 

    <p>{{ topping.text }} </p>

{% empty%} 
<li> There are no toppings on this pizza.</li>
{% endfor %}
{% if pizza.header_image %}
<img src="{{ pizza.header_image.url }}" class="img-thumbnail" width="400" height="350"/>
{% endif %} 


<h4 style="color:white;">Customer Comments:</h4>
{% for comment in comments %} 
    <div class="card mb-3">
        <h4 class="card-header">
            {{ comment.date_added | date:'M d, Y H:i' }}
        </h4>
        <div class="card-body">
            {{ comment.text | linebreaks }}
        </div>
    </div>
{% empty %} 
    <p> There are no comments for this pizza. </p>
{% endfor %}

<p> 
    <a href="{% url 'MainApp:new_comment' pizza.id %}">Add a new comment</a>
</p>


{% endblock content %} 

MainApp/templates/mainapp/pizzas.html
{% extends 'MainApp/base.html' %}

{% block page_header %} 
<h1>Pizzas</h1>
{% endblock page_header %} 

{% block content %} 
<ul style="color:white;">
    {% for pizza in pizzas %} 
        <li><h3>
            <a href="{% url 'MainApp:pizza' pizza.id %}"> {{ pizza }}</a>
        </li></h3>
    {% empty%} 
        <li><h3>No pizzas have been created yet.</h3></li>
    {% endfor %}

</ul>

{% endblock content %} z